# Generated by Django 2.1.7 on 2019-03-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(null=True)),
                ('saida', models.DateTimeField(null=True)),
                ('quantidade', models.IntegerField()),
                ('fk_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estoque')),
            ],
        ),
    ]
