# Generated by Django 2.1.7 on 2019-03-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='fk_codigo',
        ),
        migrations.AddField(
            model_name='historico',
            name='movimentacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estoque'),
        ),
    ]
