# Generated by Django 2.1.7 on 2019-03-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190317_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='movimentacao',
        ),
        migrations.AddField(
            model_name='historico',
            name='fk_codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao', to='core.Estoque'),
        ),
    ]
